export const fallbackBarterTasks = [
  {
    id: 'barter-001',
    title: 'Web Design for Home Cleaning',
    description: 'I can create a professional website for your cleaning business in exchange for bi-weekly house cleaning',
    category: 'Skills Exchange',
    type: 'barter',
    offering: 'Professional website design (WordPress, custom graphics)',
    seeking: 'Bi-weekly house cleaning service (4 hours each)',
    location: 'San Francisco, CA',
    time_commitment: '20 hours of design work',
    requirements: ['Portfolio review', 'Initial consultation', 'Ongoing communication'],
    distance_from_user: 2.3,
    skills_offered: ['Web Development', 'Graphic Design', 'SEO Optimization'],
    skills_needed: ['House Cleaning', 'Deep Cleaning', 'Organizing']
  },
  {
    id: 'barter-002',
    title: 'Photography for Accounting Services',
    description: 'Professional photographer offering event/portrait sessions in exchange for bookkeeping and tax preparation',
    category: 'Professional Services',
    type: 'barter',
    offering: 'Professional photography sessions (2-3 events or portraits)',
    seeking: 'Annual bookkeeping and tax preparation services',
    location: 'San Francisco Bay Area',
    time_commitment: '15-20 hours of photography',
    requirements: ['Professional equipment provided', 'Edited photos included', 'Service agreement'],
    distance_from_user: 5.1,
    skills_offered: ['Wedding Photography', 'Portrait Photography', 'Event Coverage'],
    skills_needed: ['Bookkeeping', 'Tax Preparation', 'Financial Planning']
  },
  {
    id: 'barter-003',
    title: 'Tutoring for Home Repairs',
    description: 'Math and science tutoring for high school students in exchange for home maintenance and repair work',
    category: 'Education & Skills',
    type: 'barter',
    offering: 'Math/Science tutoring (algebra, chemistry, physics) - 2 hours/week',
    seeking: 'Home maintenance, plumbing fixes, electrical work',
    location: 'Peninsula Area',
    time_commitment: '8-10 hours monthly tutoring',
    requirements: ['Teaching credentials', 'References available', 'Flexible scheduling'],
    distance_from_user: 7.8,
    skills_offered: ['Mathematics', 'Science Education', 'Test Prep'],
    skills_needed: ['Plumbing', 'Electrical Work', 'General Handyman']
  },
  {
    id: 'barter-004',
    title: 'Cooking Lessons for Language Translation',
    description: 'Professional chef offering cooking lessons in exchange for document translation services',
    category: 'Creative Exchange',
    type: 'barter',
    offering: 'Private cooking lessons (Italian cuisine, 4 sessions)',
    seeking: 'Translation services (English to Spanish, business documents)',
    location: 'South Bay',
    time_commitment: '8 hours of instruction',
    requirements: ['Professional kitchen available', 'Recipe materials included', 'Hands-on teaching'],
    distance_from_user: 12.5,
    skills_offered: ['Italian Cooking', 'Culinary Arts', 'Recipe Development'],
    skills_needed: ['Spanish Translation', 'Business Writing', 'Document Review']
  }
]