export const fallbackCommunityTasks = [
  {
    id: 'community-001',
    title: 'Neighborhood Park Cleanup',
    description: 'Join neighbors to pick up litter and maintain our local park',
    category: 'Community',
    type: 'community',
    payout: 35,
    location: 'Local Park',
    city: 'San Francisco',
    state: 'CA',
    zipCode: '94102',
    coordinates: { lat: 37.7749, lng: -122.4194 },
    radius_miles: 5,
    time_commitment: '2-3 hours',
    requirements: ['Work gloves', 'Trash bags (provided)', 'Before/after photos'],
    organizer: 'Community Leader',
    participants_needed: 8,
    current_participants: 3,
    deadline: '7 days',
    distance_from_user: 2.1
  },
  {
    id: 'community-002', 
    title: 'Community Garden Setup',
    description: 'Help set up raised beds and plant vegetables for the neighborhood',
    category: 'Community',
    type: 'community',
    payout: 45,
    location: 'Community Center',
    city: 'San Francisco', 
    state: 'CA',
    zipCode: '94103',
    coordinates: { lat: 37.7849, lng: -122.4094 },
    radius_miles: 10,
    time_commitment: '3-4 hours',
    requirements: ['Gardening gloves', 'Work clothes', 'Progress photos'],
    organizer: 'Garden Committee',
    participants_needed: 12,
    current_participants: 5,
    deadline: '14 days',
    distance_from_user: 3.8
  },
  {
    id: 'community-003',
    title: 'Food Drive Collection',
    description: 'Organize and collect donations for local food bank',
    category: 'Community',
    type: 'community', 
    payout: 28,
    location: 'Various Locations',
    city: 'San Francisco',
    state: 'CA',
    zipCode: '94104',
    coordinates: { lat: 37.7949, lng: -122.3994 },
    radius_miles: 15,
    time_commitment: '2-3 hours',
    requirements: ['Transportation', 'Collection boxes', 'Donation photos'],
    organizer: 'Food Bank Coordinator',
    participants_needed: 6,
    current_participants: 2,
    deadline: '10 days',
    distance_from_user: 5.2
  }
]