export const fallbackCorporateTasks = [
  {
    id: 'corporate-001',
    title: 'Data Entry for Local Business',
    description: 'Enter customer information from paper forms into digital database',
    category: 'Data Entry',
    type: 'corporate',
    payout: 85,
    location: 'Remote',
    time_commitment: 'Part-time (4-6 hours)',
    requirements: ['Computer with Excel', 'Attention to detail', 'Progress screenshots'],
    company: 'TechCorp Solutions',
    deadline: '14 days',
    positions_available: 3,
    current_applicants: 1,
    experience_level: 'Entry Level',
    verification_required: true
  },
  {
    id: 'corporate-002',
    title: 'Social Media Content Creation',
    description: 'Create Instagram posts and captions for small business marketing',
    category: 'Marketing',
    type: 'corporate',
    payout: 150,
    location: 'Hybrid',
    time_commitment: 'Project-based (8-10 hours)',
    requirements: ['Design software knowledge', 'Social media experience', 'Portfolio samples'],
    company: 'Local Marketing Agency',
    deadline: '21 days',
    positions_available: 2,
    current_applicants: 4,
    experience_level: 'Intermediate',
    verification_required: true
  },
  {
    id: 'corporate-003',
    title: 'Customer Survey Calls',
    description: 'Conduct phone surveys with existing customers about service satisfaction',
    category: 'Customer Service',
    type: 'corporate',
    payout: 120,
    location: 'Remote',
    time_commitment: 'Flexible (6-8 hours)',
    requirements: ['Phone access', 'Professional communication', 'Survey results'],
    company: 'Business Consulting Group',
    deadline: '10 days',
    positions_available: 5,
    current_applicants: 2,
    experience_level: 'Entry Level',
    verification_required: true
  }
]