// Complete set of 25 everyday adult tasks for Solo category
// These are activities that most adults do regularly regardless of age or skill level

import { TaskData } from './taskData'

export const everydayTasks: TaskData[] = [
  // Daily Household Tasks (8 tasks)
  {
    id: 'solo-001',
    title: 'Wash Dishes and Clean Kitchen',
    description: 'Wash all dishes, clean counters, and tidy kitchen. Take before/after photos showing your sparkling clean kitchen space.',
    type: 'solo',
    category: 'Household',
    payout: 8,
    max_participants: 1,
    current_participants: 0,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: null,
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'easy',
    time_estimate: '30 minutes',
    location_type: 'home',
    materials_needed: ['Dish soap', 'Sponge/dishcloth', 'Towel'],
    daily_limit: 5,
    completion_time_hours: 24, // 24 hours to complete
    daily_completed: 0
  },
  {
    id: 'solo-002',
    title: 'Do a Load of Laundry - Wash, Dry, Fold',
    description: 'Complete laundry cycle from start to finish. Sort, wash, dry, and fold clothes. Show organized final result.',
    type: 'solo',
    category: 'Household',
    payout: 12,
    max_participants: 1,
    current_participants: 0,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: null,
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'easy',
    time_estimate: '45 minutes',
    location_type: 'home',
    materials_needed: ['Laundry detergent', 'Access to washer/dryer'],
    daily_limit: 5,
    completion_time_hours: 24,
    daily_completed: 0
  },
  {
    id: 'solo-003',
    title: 'Vacuum Living Areas',
    description: 'Vacuum all carpets and rugs in main living spaces. Move furniture as needed and get corners and edges clean.',
    type: 'solo',
    category: 'Household',
    payout: 10,
    max_participants: 1,
    current_participants: 0,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: null,
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'easy',
    time_estimate: '30 minutes',
    location_type: 'home',
    materials_needed: ['Vacuum cleaner'],
    daily_limit: 5,
    completion_time_hours: 24,
    daily_completed: 0
  },
  {
    id: 'solo-004',
    title: 'Make Beds and Tidy Bedrooms',
    description: 'Make all beds in the house and do quick bedroom tidying. Put away clothes, clear surfaces, and fluff pillows.',
    type: 'solo',
    category: 'Household',
    payout: 6,
    max_participants: 1,
    current_participants: 0,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: null,
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'easy',
    time_estimate: '15 minutes',
    location_type: 'home',
    materials_needed: ['Fresh linens if needed']
  },
  {
    id: 'solo-005',
    title: 'Take Out Trash and Recycling',
    description: 'Empty all trash cans in the house, take out garbage and recycling to bins. Replace trash bags and tidy up around bins.',
    type: 'solo',
    category: 'Household',
    payout: 5,
    max_participants: 1,
    current_participants: 0,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: null,
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'easy',
    time_estimate: '10 minutes',
    location_type: 'home',
    materials_needed: ['Trash bags']
  },
  {
    id: 'solo-006',
    title: 'Wipe Down Bathrooms',
    description: 'Clean and wipe down bathroom surfaces - sink, counter, mirror, toilet. Quick but thorough bathroom refresh.',
    type: 'solo',
    category: 'Household',
    payout: 8,
    max_participants: 1,
    current_participants: 0,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: null,
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'easy',
    time_estimate: '20 minutes',
    location_type: 'home',
    materials_needed: ['Cleaning wipes or spray', 'Paper towels']
  },
  {
    id: 'solo-007',
    title: 'Organize One Room/Closet',
    description: 'Pick one room or closet and organize it thoroughly. Put everything in its place, declutter, and make it functional.',
    type: 'solo',
    category: 'Household',
    payout: 15,
    max_participants: 1,
    current_participants: 0,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: null,
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'easy',
    time_estimate: '1 hour',
    location_type: 'home',
    materials_needed: ['Storage containers (optional)', 'Labels (optional)']
  },
  {
    id: 'solo-008',
    title: 'Meal Prep for Tomorrow',
    description: 'Prepare tomorrow\'s meals or ingredients. Could be cutting vegetables, prepping lunches, or planning dinner ingredients.',
    type: 'solo',
    category: 'Household',
    payout: 20,
    max_participants: 1,
    current_participants: 0,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: null,
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'easy',
    time_estimate: '1 hour',
    location_type: 'home',
    materials_needed: ['Food ingredients', 'Storage containers', 'Kitchen utensils']
  },

  // Transportation & Errands (5 tasks)
  {
    id: 'solo-009',
    title: 'Grocery Shopping Trip',
    description: 'Complete grocery shopping for the week. Make a list, shop efficiently, and organize groceries at home.',
    type: 'solo',
    category: 'Errands',
    payout: 15,
    max_participants: 1,
    current_participants: 0,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: null,
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'easy',
    time_estimate: '1 hour',
    location_type: 'local',
    materials_needed: ['Transportation', 'Grocery list', 'Payment method']
  },
  {
    id: 'solo-010',
    title: 'Drop Kids at School',
    description: 'Get kids ready and safely drop them off at school on time. Document the successful drop-off completion.',
    type: 'solo',
    category: 'Errands',
    payout: 8,
    max_participants: 1,
    current_participants: 0,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: null,
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'easy',
    time_estimate: '30 minutes',
    location_type: 'local',
    materials_needed: ['Transportation', 'Kids\' school items']
  },
  {
    id: 'solo-011',
    title: 'Pick Up Dry Cleaning',
    description: 'Go to dry cleaner and pick up clean clothes. Check items and transport them home safely.',
    type: 'solo',
    category: 'Errands',
    payout: 6,
    max_participants: 1,
    current_participants: 0,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: null,
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'easy',
    time_estimate: '20 minutes',
    location_type: 'local',
    materials_needed: ['Transportation', 'Dry cleaning ticket', 'Payment method']
  },
  {
    id: 'solo-012',
    title: 'Gas Station Fill-Up',
    description: 'Fill up your car with gas and clean windshield. Take photo of full gas gauge as completion proof.',
    type: 'solo',
    category: 'Errands',
    payout: 5,
    max_participants: 1,
    current_participants: 0,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: null,
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'easy',
    time_estimate: '15 minutes',
    location_type: 'local',
    materials_needed: ['Car', 'Payment method']
  },
  {
    id: 'solo-013',
    title: 'Post Office or Bank Run',
    description: 'Complete tasks at post office or bank - mail packages, deposit checks, withdraw cash, etc.',
    type: 'solo',
    category: 'Errands',
    payout: 8,
    max_participants: 1,
    current_participants: 0,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: null,
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'easy',
    time_estimate: '30 minutes',
    location_type: 'local',
    materials_needed: ['Transportation', 'ID', 'Items to mail/deposit']
  },

  // Health & Wellness (6 tasks)
  {
    id: 'solo-014',
    title: '30-Minute Walk Outside',
    description: 'Take a 30-minute walk outdoors for exercise and fresh air. Track your route and share completion photo.',
    type: 'solo',
    category: 'Health & Wellness',
    payout: 8,
    max_participants: 1,
    current_participants: 0,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: null,
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'easy',
    time_estimate: '30 minutes',
    location_type: 'local',
    materials_needed: ['Comfortable walking shoes', 'Weather-appropriate clothing']
  },
  {
    id: 'solo-015',
    title: 'Yoga Session (30 min)',
    description: 'Complete a 30-minute yoga session at home or studio. Focus on flexibility, balance, and mindfulness.',
    type: 'solo',
    category: 'Health & Wellness',
    payout: 12,
    max_participants: 1,
    current_participants: 0,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: null,
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'easy',
    time_estimate: '30 minutes',
    location_type: 'home',
    materials_needed: ['Yoga mat', 'Comfortable clothing']
  },
  {
    id: 'solo-016',
    title: 'Meditation (15-20 min)',
    description: 'Practice mindfulness meditation for 15-20 minutes. Use an app or simply focus on breathing and being present.',
    type: 'solo',
    category: 'Health & Wellness',
    payout: 6,
    max_participants: 1,
    current_participants: 0,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: null,
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'easy',
    time_estimate: '20 minutes',
    location_type: 'home',
    materials_needed: ['Quiet space', 'Meditation app (optional)']
  },
  {
    id: 'solo-017',
    title: 'Prep Healthy Snacks for Week',
    description: 'Prepare healthy snacks for the upcoming week. Wash fruit, portion nuts, or prep veggie sticks.',
    type: 'solo',
    category: 'Health & Wellness',
    payout: 10,
    max_participants: 1,
    current_participants: 0,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: null,
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'easy',
    time_estimate: '30 minutes',
    location_type: 'home',
    materials_needed: ['Fresh fruits/vegetables', 'Storage containers', 'Kitchen utensils']
  },
  {
    id: 'solo-018',
    title: 'Take Vitamins/Daily Medications',
    description: 'Take your daily vitamins or medications as prescribed. Organize pill organizer for the week if needed.',
    type: 'solo',
    category: 'Health & Wellness',
    payout: 3,
    max_participants: 1,
    current_participants: 0,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: null,
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'easy',
    time_estimate: '5 minutes',
    location_type: 'home',
    materials_needed: ['Vitamins/medications', 'Water', 'Pill organizer (optional)']
  },
  {
    id: 'solo-019',
    title: 'Drink 8 Glasses of Water Today',
    description: 'Stay hydrated by drinking 8 full glasses of water throughout the day. Track your progress and stay consistent.',
    type: 'solo',
    category: 'Health & Wellness',
    payout: 4,
    max_participants: 1,
    current_participants: 0,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: null,
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'easy',
    time_estimate: 'Throughout day',
    location_type: 'home',
    materials_needed: ['Water bottle or glasses', 'Fresh water']
  },

  // Personal Care (3 tasks)
  {
    id: 'solo-020',
    title: 'Complete Skincare Routine',
    description: 'Do your full morning or evening skincare routine. Cleanse, moisturize, and apply any treatments you use.',
    type: 'solo',
    category: 'Personal Care',
    payout: 5,
    max_participants: 1,
    current_participants: 0,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: null,
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'easy',
    time_estimate: '10 minutes',
    location_type: 'home',
    materials_needed: ['Skincare products', 'Clean towel']
  },
  {
    id: 'solo-021',
    title: 'Exercise for 30 Minutes',
    description: 'Complete 30 minutes of exercise - could be cardio, strength training, dancing, or any physical activity you enjoy.',
    type: 'solo',
    category: 'Personal Care',
    payout: 10,
    max_participants: 1,
    current_participants: 0,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: null,
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'easy',
    time_estimate: '30 minutes',
    location_type: 'home',
    materials_needed: ['Workout clothes', 'Exercise equipment (optional)']
  },
  {
    id: 'solo-022',
    title: 'Read for 30 Minutes',
    description: 'Spend 30 minutes reading a book, magazine, or articles. Focus on learning or enjoying literature.',
    type: 'solo',
    category: 'Personal Care',
    payout: 8,
    max_participants: 1,
    current_participants: 0,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: null,
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'easy',
    time_estimate: '30 minutes',
    location_type: 'home',
    materials_needed: ['Book/magazine/device', 'Comfortable reading spot']
  },

  // Productive Activities (3 tasks)
  {
    id: 'solo-023',
    title: 'Pay Bills Online',
    description: 'Log in to accounts and pay monthly bills - utilities, credit cards, loans, subscriptions. Keep track of what you paid.',
    type: 'solo',
    category: 'Productive',
    payout: 8,
    max_participants: 1,
    current_participants: 0,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: null,
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'easy',
    time_estimate: '20 minutes',
    location_type: 'home',
    materials_needed: ['Computer/phone', 'Account login info', 'Payment method']
  },
  {
    id: 'solo-024',
    title: 'Plan Tomorrow\'s Schedule',
    description: 'Review calendar and plan tomorrow\'s activities. Set priorities, check appointments, and organize your day.',
    type: 'solo',
    category: 'Productive',
    payout: 6,
    max_participants: 1,
    current_participants: 0,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: null,
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'easy',
    time_estimate: '15 minutes',
    location_type: 'home',
    materials_needed: ['Calendar/planner', 'Phone/computer']
  },
  {
    id: 'solo-025',
    title: 'Call/Text Family Member',
    description: 'Reach out to a family member you haven\'t spoken to recently. Have a meaningful conversation and catch up.',
    type: 'solo',
    category: 'Productive',
    payout: 4,
    max_participants: 1,
    current_participants: 0,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: null,
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'easy',
    time_estimate: '10 minutes',
    location_type: 'home',
    materials_needed: ['Phone', 'Contact information']
  }
]