// Comprehensive task database for BittieTasks platform
// Real earning opportunities for parents to monetize daily activities

export interface TaskData {
  id: string
  title: string
  description: string
  type: 'solo' | 'shared' | 'self_care'
  category: string
  payout: number
  max_participants: number
  current_participants: number
  creator_id: string
  status: 'active' | 'completed' | 'cancelled'
  created_at: string
  deadline: string | null
  is_sponsored: boolean
  sponsor_name: string | null
  difficulty: 'easy' | 'medium' | 'hard'
  time_estimate: string
  location_type: 'home' | 'local' | 'online'
  age_group?: string
  materials_needed?: string[]
}

// Import everyday adult tasks
import { everydayTasks } from './everydayTasks'

// 25 Solo Tasks - Everyday adult activities that anyone can do
export const soloTasks: TaskData[] = everydayTasks

// Legacy complex tasks moved to community/barter categories for specialized users
export const legacyTasks: TaskData[] = [
  // Daily Household Tasks (8 tasks)
  {
    id: 'solo-001',
    title: 'Wash Dishes and Clean Kitchen',
    description: 'Wash all dishes, clean counters, and tidy kitchen. Take before/after photos showing your sparkling clean kitchen space.',
    type: 'solo',
    category: 'Household',
    payout: 8,
    max_participants: 1,
    current_participants: 0,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: null,
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'easy',
    time_estimate: '30 minutes',
    location_type: 'home',
    materials_needed: ['Dish soap', 'Sponge/dishcloth', 'Towel']
  },
  {
    id: 'solo-002',
    title: 'Do a Load of Laundry - Wash, Dry, Fold',
    description: 'Complete laundry cycle from start to finish. Sort, wash, dry, and fold clothes. Show organized final result.',
    type: 'solo',
    category: 'Household',
    payout: 12,
    max_participants: 1,
    current_participants: 0,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: null,
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'easy',
    time_estimate: '45 minutes',
    location_type: 'home',
    materials_needed: ['Laundry detergent', 'Access to washer/dryer']
  },
  {
    id: 'solo-003',
    title: 'Vacuum Living Areas',
    description: 'Vacuum all carpets and rugs in main living spaces. Move furniture as needed and get corners and edges clean.',
    type: 'solo',
    category: 'Household',
    payout: 10,
    max_participants: 1,
    current_participants: 0,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: null,
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'easy',
    time_estimate: '30 minutes',
    location_type: 'home',
    materials_needed: ['Vacuum cleaner']
  },
  {
    id: 'solo-004',
    title: 'Make Beds and Tidy Bedrooms',
    description: 'Make all beds in the house and do quick bedroom tidying. Put away clothes, clear surfaces, and fluff pillows.',
    type: 'solo',
    category: 'Household',
    payout: 6,
    max_participants: 1,
    current_participants: 0,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: null,
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'easy',
    time_estimate: '15 minutes',
    location_type: 'home',
    materials_needed: ['Fresh linens if needed']
  },
  {
    id: 'solo-005',
    title: 'Take Out Trash and Recycling',
    description: 'Empty all trash cans in the house, take out garbage and recycling to bins. Replace trash bags and tidy up around bins.',
    type: 'solo',
    category: 'Household',
    payout: 5,
    max_participants: 1,
    current_participants: 0,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: null,
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'easy',
    time_estimate: '10 minutes',
    location_type: 'home',
    materials_needed: ['Trash bags']
  },
  {
    id: 'solo-006',
    title: 'Wipe Down Bathrooms',
    description: 'Clean and wipe down bathroom surfaces - sink, counter, mirror, toilet. Quick but thorough bathroom refresh.',
    type: 'solo',
    category: 'Household',
    payout: 8,
    max_participants: 1,
    current_participants: 0,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: null,
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'easy',
    time_estimate: '20 minutes',
    location_type: 'home',
    materials_needed: ['Cleaning wipes or spray', 'Paper towels']
  },
  {
    id: 'solo-007',
    title: 'Create Reading Comprehension Games',
    description: 'Design interactive reading games that make comprehension fun for reluctant readers. Include different difficulty levels and themes.',
    type: 'solo',
    category: 'Education',
    payout: 48,
    max_participants: 1,
    current_participants: 0,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: null,
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'medium',
    time_estimate: '5-6 hours',
    location_type: 'home',
    age_group: '6-10 years',
    materials_needed: ['Craft materials', 'Books', 'Game pieces']
  },
  {
    id: 'solo-008',
    title: 'Design Math Practice Games for Different Learning Styles',
    description: 'Create visual, auditory, and kinesthetic math games that make practice enjoyable. Focus on common problem areas for elementary students.',
    type: 'solo',
    category: 'Education',
    payout: 52,
    max_participants: 1,
    current_participants: 0,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: null,
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'medium',
    time_estimate: '6-7 hours',
    location_type: 'home',
    age_group: '7-11 years',
    materials_needed: ['Craft supplies', 'Math manipulatives', 'Game boards']
  },

  // Health & Wellness (8 tasks)
  {
    id: 'solo-009',
    title: 'Document Family Fitness Routine for Small Spaces',
    description: 'Create a comprehensive fitness program that families can do together in apartments or small homes. Include modifications for different ages.',
    type: 'solo',
    category: 'Health & Fitness',
    payout: 45,
    max_participants: 1,
    current_participants: 0,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: null,
    is_sponsored: true,
    sponsor_name: 'ActiveFamily Wellness',
    difficulty: 'medium',
    time_estimate: '4-5 hours',
    location_type: 'home',
    materials_needed: ['Exercise equipment (optional)', 'Camera', 'Measurement tools']
  },
  {
    id: 'solo-010',
    title: 'Create Healthy Snack Preparation Guide',
    description: 'Develop week-long healthy snack prep plans with kid-friendly options. Include shopping lists, prep instructions, and storage tips.',
    type: 'solo',
    category: 'Nutrition',
    payout: 38,
    max_participants: 1,
    current_participants: 0,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: null,
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'easy',
    time_estimate: '3-4 hours',
    location_type: 'home',
    materials_needed: ['Fresh ingredients', 'Storage containers', 'Kitchen tools']
  },

  // Technology & Digital (7 tasks)
  {
    id: 'solo-011',
    title: 'Set Up Family Digital Organization System',
    description: 'Create a comprehensive system for organizing family photos, documents, and memories digitally. Include backup strategies and sharing protocols.',
    type: 'solo',
    category: 'Digital Organization',
    payout: 58,
    max_participants: 1,
    current_participants: 0,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: null,
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'medium',
    time_estimate: '5-7 hours',
    location_type: 'home',
    materials_needed: ['Computer/tablet', 'External storage', 'Family photos/documents']
  },
  {
    id: 'solo-012',
    title: 'Create Screen Time Management Plan',
    description: 'Develop a balanced approach to screen time that includes educational content, creativity time, and family interaction. Document what works.',
    type: 'solo',
    category: 'Digital Wellness',
    payout: 42,
    max_participants: 1,
    current_participants: 0,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: null,
    is_sponsored: true,
    sponsor_name: 'DigitalBalance Kids',
    difficulty: 'medium',
    time_estimate: '4-5 hours',
    location_type: 'home',
    materials_needed: ['Timer', 'Activity planning sheets', 'Device management tools']
  },

  // Financial & Budgeting (5 tasks)
  {
    id: 'solo-013',
    title: 'Design Kids\' Allowance and Chore System',
    description: 'Create an age-appropriate system for teaching kids about money through chores and allowances. Include tracking methods and saving goals.',
    type: 'solo',
    category: 'Financial Education',
    payout: 35,
    max_participants: 1,
    current_participants: 0,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: null,
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'easy',
    time_estimate: '2-3 hours',
    location_type: 'home',
    age_group: '5-15 years',
    materials_needed: ['Chart materials', 'Play money (optional)', 'Tracking sheets']
  },

  // Seasonal & Holiday (5 tasks)
  {
    id: 'solo-014',
    title: 'Plan Month-by-Month Family Traditions Calendar',
    description: 'Create meaningful family traditions for each month that build memories without breaking the budget. Include preparation guides and shopping lists.',
    type: 'solo',
    category: 'Family Traditions',
    payout: 48,
    max_participants: 1,
    current_participants: 0,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: null,
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'medium',
    time_estimate: '5-6 hours',
    location_type: 'home',
    materials_needed: ['Calendar', 'Planning materials', 'Craft supplies']
  },

  // More Solo Tasks - Additional income opportunities
  {
    id: 'solo-015',
    title: 'Create DIY Sensory Play Activities Guide',
    description: 'Design 15 sensory activities for toddlers using safe household materials. Perfect for developmental play and parent stress relief.',
    type: 'solo',
    category: 'Child Development',
    payout: 38,
    max_participants: 1,
    current_participants: 0,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: null,
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'easy',
    time_estimate: '4-5 hours',
    location_type: 'home',
    age_group: '1-4 years',
    materials_needed: ['Safe household items', 'Storage containers', 'Camera for documentation']
  },
  {
    id: 'solo-016',
    title: 'Document Toddler Sleep Training Journey',
    description: 'Share your successful sleep training experience with detailed logs, methods used, and timeline. Help other exhausted parents.',
    type: 'solo',
    category: 'Parenting Support',
    payout: 55,
    max_participants: 1,
    current_participants: 0,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: null,
    is_sponsored: true,
    sponsor_name: 'RestfulNights Baby',
    difficulty: 'medium',
    time_estimate: '3-4 hours documentation',
    location_type: 'home',
    age_group: '0-3 years',
    materials_needed: ['Sleep logs', 'Timer', 'Documentation materials']
  },
  {
    id: 'solo-017',
    title: 'Design Outdoor Nature Scavenger Hunts',
    description: 'Create seasonal scavenger hunts for local parks and nature areas. Include educational components and safety guidelines.',
    type: 'solo',
    category: 'Outdoor Activities',
    payout: 32,
    max_participants: 1,
    current_participants: 0,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: null,
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'easy',
    time_estimate: '3-4 hours',
    location_type: 'local',
    age_group: '4-12 years',
    materials_needed: ['Nature guides', 'Collection bags', 'Activity sheets']
  },
  {
    id: 'solo-018',
    title: 'Create Behavior Chart System That Actually Works',
    description: 'Design age-appropriate behavior charts with rewards that motivate without breaking the budget. Include troubleshooting guide.',
    type: 'solo',
    category: 'Parenting Support',
    payout: 42,
    max_participants: 1,
    current_participants: 0,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: null,
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'medium',
    time_estimate: '4-5 hours',
    location_type: 'home',
    age_group: '3-10 years',
    materials_needed: ['Chart materials', 'Stickers/rewards', 'Tracking system']
  },
  {
    id: 'solo-019',
    title: 'Organize Kids\' Digital Photo Albums by Year',
    description: 'Create beautiful digital photo albums organized by child and year. Include printing guides and sharing tips for grandparents.',
    type: 'solo',
    category: 'Digital Organization',
    payout: 45,
    max_participants: 1,
    current_participants: 0,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: null,
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'medium',
    time_estimate: '6-8 hours',
    location_type: 'home',
    materials_needed: ['Computer', 'Photo organization software', 'External storage']
  },
  {
    id: 'solo-020',
    title: 'Design Rainy Day Activity Binder',
    description: 'Create comprehensive binder with 50+ indoor activities for different ages. Include mess-free and educational options.',
    type: 'solo',
    category: 'Activity Planning',
    payout: 38,
    max_participants: 1,
    current_participants: 0,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: null,
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'medium',
    time_estimate: '5-6 hours',
    location_type: 'home',
    age_group: 'All ages',
    materials_needed: ['Binder', 'Activity supplies', 'Printed materials']
  }
]

// 30+ Community Tasks - Neighborhood sharing opportunities
export const communityTasks: TaskData[] = [
  // Childcare & Education Sharing (10 tasks)
  {
    id: 'community-001',
    title: 'Coordinate Neighborhood Reading Circle',
    description: 'Organize weekly reading sessions where kids share favorite books. Rotate hosting between families, split snack costs, and create a neighborhood library.',
    type: 'shared',
    category: 'Education',
    payout: 25,
    max_participants: 6,
    current_participants: 2,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'easy',
    time_estimate: '2 hours weekly',
    location_type: 'local',
    age_group: '5-12 years',
    materials_needed: ['Books', 'Snacks', 'Comfortable seating']
  },
  {
    id: 'community-002',
    title: 'Organize Science Experiment Playdate',
    description: 'Host hands-on science experiments for neighborhood kids. Parents contribute $15 each for materials. Share the learning experience and split supervision duties.',
    type: 'shared',
    category: 'Education',
    payout: 35,
    max_participants: 4,
    current_participants: 1,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    is_sponsored: true,
    sponsor_name: 'STEM Learning Lab',
    difficulty: 'medium',
    time_estimate: '3 hours',
    location_type: 'local',
    age_group: '6-10 years',
    materials_needed: ['Science experiment kits', 'Safety goggles', 'Cleaning supplies']
  },
  {
    id: 'community-003',
    title: 'Start Neighborhood Homework Help Exchange',
    description: 'Create a system where parents with different expertise help each other\'s kids with homework. Math parent helps with math, writer helps with essays, etc.',
    type: 'shared',
    category: 'Education',
    payout: 30,
    max_participants: 8,
    current_participants: 3,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: null,
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'easy',
    time_estimate: '1-2 hours per session',
    location_type: 'local',
    age_group: '8-16 years',
    materials_needed: ['Study materials', 'Notebooks', 'Computer access']
  },

  // Meal Sharing & Cooking (8 tasks)
  {
    id: 'community-004',
    title: 'Coordinate Weekly Meal Train for Busy Families',
    description: 'Organize 5 families to cook extra portions one night each week. Everyone gets 4 nights off from cooking while contributing one meal.',
    type: 'shared',
    category: 'Meal Sharing',
    payout: 40,
    max_participants: 5,
    current_participants: 2,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'medium',
    time_estimate: '2-3 hours weekly',
    location_type: 'local',
    materials_needed: ['Cooking ingredients', 'Food containers', 'Delivery coordination']
  },
  {
    id: 'community-005',
    title: 'Host Kids\' Cooking Class Exchange',
    description: 'Teach neighborhood kids to cook while parents rotate teaching duties. Each family teaches their signature kid-friendly recipe.',
    type: 'shared',
    category: 'Education',
    payout: 32,
    max_participants: 6,
    current_participants: 4,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000).toISOString(),
    is_sponsored: true,
    sponsor_name: 'Young Chefs Academy',
    difficulty: 'medium',
    time_estimate: '2.5 hours per session',
    location_type: 'local',
    age_group: '6-14 years',
    materials_needed: ['Cooking ingredients', 'Child-safe utensils', 'Aprons']
  },

  // Transportation & Logistics (7 tasks)
  {
    id: 'community-006',
    title: 'Organize School Pickup Carpool Network',
    description: 'Coordinate reliable carpool system for after-school activities. Split gas costs and reduce individual driving time by 75%.',
    type: 'shared',
    category: 'Transportation',
    payout: 28,
    max_participants: 8,
    current_participants: 5,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: null,
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'easy',
    time_estimate: 'Daily 30-45 minutes',
    location_type: 'local',
    materials_needed: ['Reliable vehicle', 'Car seats if needed', 'Communication app']
  },
  {
    id: 'community-007',
    title: 'Coordinate Neighborhood Grocery Run',
    description: 'One person does grocery shopping for 6 families weekly. Split gas and time costs. Perfect for busy parents who want to outsource shopping.',
    type: 'shared',
    category: 'Household Management',
    payout: 45,
    max_participants: 6,
    current_participants: 3,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'medium',
    time_estimate: '2-3 hours weekly',
    location_type: 'local',
    materials_needed: ['Shopping lists', 'Payment coordination', 'Coolers for transport']
  },

  // Event Planning & Parties (5 tasks)
  {
    id: 'community-008',
    title: 'Plan Joint Birthday Party for Same-Month Kids',
    description: 'Combine birthday celebrations for kids born in the same month. Split venue, decoration, and entertainment costs while creating a bigger celebration.',
    type: 'shared',
    category: 'Event Planning',
    payout: 55,
    max_participants: 4,
    current_participants: 2,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'medium',
    time_estimate: '6-8 hours planning',
    location_type: 'local',
    age_group: 'Same-age groups',
    materials_needed: ['Party supplies', 'Venue rental', 'Entertainment booking']
  },

  // More Community Tasks - Neighborhood collaboration
  {
    id: 'community-009',
    title: 'Organize Neighborhood Skill Share Network',
    description: 'Create a system where parents teach each other skills - guitar lessons, home repair, language practice, etc. Everyone contributes and benefits.',
    type: 'shared',
    category: 'Skill Exchange',
    payout: 35,
    max_participants: 12,
    current_participants: 7,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: null,
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'medium',
    time_estimate: '2 hours per session',
    location_type: 'local',
    materials_needed: ['Skill-specific materials', 'Teaching space', 'Coordination system']
  },
  {
    id: 'community-010',
    title: 'Coordinate Family Game Night Rotation',
    description: 'Host weekly family game nights rotating between 6 houses. Split snack costs and game library. Perfect for building community.',
    type: 'shared',
    category: 'Family Entertainment',
    payout: 22,
    max_participants: 6,
    current_participants: 4,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: null,
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'easy',
    time_estimate: '3 hours weekly',
    location_type: 'local',
    age_group: 'Family friendly',
    materials_needed: ['Board games', 'Snacks', 'Hosting space']
  },
  {
    id: 'community-011',
    title: 'Start Neighborhood Tool Library',
    description: 'Organize shared tool collection for home projects. Split cost of new tools and maintenance. Save money while building community.',
    type: 'shared',
    category: 'Resource Sharing',
    payout: 40,
    max_participants: 10,
    current_participants: 6,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: null,
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'medium',
    time_estimate: 'Ongoing maintenance',
    location_type: 'local',
    materials_needed: ['Storage space', 'Tool inventory system', 'Basic tools']
  },
  {
    id: 'community-012',
    title: 'Organize Bulk Buying Group for Families',
    description: 'Coordinate bulk purchases of household essentials - diapers, paper products, cleaning supplies. Split costs and storage responsibilities.',
    type: 'shared',
    category: 'Household Management',
    payout: 38,
    max_participants: 8,
    current_participants: 5,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'medium',
    time_estimate: '2-3 hours monthly',
    location_type: 'local',
    materials_needed: ['Storage space', 'Transportation', 'Cost calculation system']
  },
  {
    id: 'community-013',
    title: 'Create Neighborhood Emergency Contact Network',
    description: 'Establish trusted network for emergency childcare, elderly check-ins, and crisis support. Include skills inventory and availability.',
    type: 'shared',
    category: 'Community Support',
    payout: 30,
    max_participants: 15,
    current_participants: 9,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: null,
    is_sponsored: true,
    sponsor_name: 'CommunityConnect Safety',
    difficulty: 'easy',
    time_estimate: '2 hours setup + ongoing',
    location_type: 'local',
    materials_needed: ['Contact information', 'Skills database', 'Communication system']
  },
  {
    id: 'community-014',
    title: 'Host Neighborhood Clean-Up Day',
    description: 'Organize quarterly neighborhood beautification with families. Include kids in age-appropriate tasks. Split costs for supplies and refreshments.',
    type: 'shared',
    category: 'Community Service',
    payout: 25,
    max_participants: 20,
    current_participants: 12,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000).toISOString(),
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'easy',
    time_estimate: '4 hours quarterly',
    location_type: 'local',
    age_group: 'All ages',
    materials_needed: ['Cleaning supplies', 'Gloves', 'Refreshments']
  },
  {
    id: 'community-015',
    title: 'Coordinate After-School Activity Sharing',
    description: 'Share transportation and costs for kids\' activities. One parent teaches art, another music, another sports - rotate weekly.',
    type: 'shared',
    category: 'Child Activities',
    payout: 35,
    max_participants: 6,
    current_participants: 3,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: null,
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'medium',
    time_estimate: '2 hours weekly',
    location_type: 'local',
    age_group: '6-12 years',
    materials_needed: ['Activity supplies', 'Transportation', 'Scheduling system']
  }
]

// 30+ Self-Care Tasks - Wellness and personal development
export const selfCareTasks: TaskData[] = [
  // Physical Wellness (10 tasks)
  {
    id: 'selfcare-001',
    title: 'Complete 30-Day Parent Fitness Challenge',
    description: 'Join other parents in a month-long fitness journey designed around busy schedules. 15-minute daily workouts with accountability partners.',
    type: 'self_care',
    category: 'Physical Wellness',
    payout: 50,
    max_participants: 10,
    current_participants: 7,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    is_sponsored: true,
    sponsor_name: 'FitParent Community',
    difficulty: 'medium',
    time_estimate: '15 minutes daily',
    location_type: 'home',
    materials_needed: ['Workout clothes', 'Water bottle', 'Phone for tracking']
  },
  {
    id: 'selfcare-002',
    title: 'Practice Daily Meditation for Stress Relief',
    description: 'Commit to 10 minutes of daily meditation using guided apps. Share experiences and techniques with other parents for mutual support.',
    type: 'self_care',
    category: 'Mental Wellness',
    payout: 35,
    max_participants: 15,
    current_participants: 12,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000).toISOString(),
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'easy',
    time_estimate: '10 minutes daily',
    location_type: 'home',
    materials_needed: ['Quiet space', 'Meditation app', 'Comfortable seating']
  },

  // Learning & Growth (8 tasks)
  {
    id: 'selfcare-003',
    title: 'Complete Online Parenting Course',
    description: 'Take a research-based parenting course and implement new strategies. Share insights and progress with accountability partners.',
    type: 'self_care',
    category: 'Personal Development',
    payout: 75,
    max_participants: 8,
    current_participants: 5,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000).toISOString(),
    is_sponsored: true,
    sponsor_name: 'Parent Education Institute',
    difficulty: 'medium',
    time_estimate: '2 hours weekly',
    location_type: 'online',
    materials_needed: ['Computer/tablet', 'Notebook', 'Course materials']
  },
  {
    id: 'selfcare-004',
    title: 'Learn New Skill During Naptime',
    description: 'Use kids\' naptime or quiet time to learn something new - language, instrument, craft, or professional skill. Track progress and celebrate milestones.',
    type: 'self_care',
    category: 'Personal Development',
    payout: 40,
    max_participants: 12,
    current_participants: 8,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString(),
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'medium',
    time_estimate: '30-45 minutes daily',
    location_type: 'home',
    materials_needed: ['Learning materials', 'Practice space', 'Progress tracking']
  },

  // Creative Expression (7 tasks)
  {
    id: 'selfcare-005',
    title: 'Start Daily Creative Practice',
    description: 'Commit to 20 minutes daily of creative expression - writing, drawing, music, or crafting. Share creations and inspire other parents.',
    type: 'self_care',
    category: 'Creative Wellness',
    payout: 45,
    max_participants: 20,
    current_participants: 14,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'easy',
    time_estimate: '20 minutes daily',
    location_type: 'home',
    materials_needed: ['Art supplies', 'Creative materials', 'Inspiration journal']
  },

  // Social Connection (5 tasks)
  {
    id: 'selfcare-006',
    title: 'Organize Parent Coffee Meetup Group',
    description: 'Host weekly coffee meetups for parents to connect, share experiences, and support each other. Rotate hosting duties and build lasting friendships.',
    type: 'self_care',
    category: 'Social Wellness',
    payout: 25,
    max_participants: 8,
    current_participants: 6,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: null,
    is_sponsored: true,
    sponsor_name: 'Community Connections Cafe',
    difficulty: 'easy',
    time_estimate: '1.5 hours weekly',
    location_type: 'local',
    materials_needed: ['Coffee/tea', 'Comfortable seating', 'Childcare coordination']
  },

  // More Self-Care Tasks - Personal wellness and growth
  {
    id: 'selfcare-007',
    title: 'Join Parent Book Club with Accountability',
    description: 'Read one personal development or parenting book monthly with other parents. Share insights and implement new strategies together.',
    type: 'self_care',
    category: 'Personal Development',
    payout: 30,
    max_participants: 12,
    current_participants: 8,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: null,
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'easy',
    time_estimate: '3-4 hours monthly',
    location_type: 'online',
    materials_needed: ['Books', 'Notebook', 'Discussion platform']
  },
  {
    id: 'selfcare-008',
    title: 'Complete Digital Detox Challenge',
    description: 'Take a structured break from social media and excessive screen time. Focus on real-world connections and mindful parenting.',
    type: 'self_care',
    category: 'Digital Wellness',
    payout: 40,
    max_participants: 25,
    current_participants: 18,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'medium',
    time_estimate: '2 weeks commitment',
    location_type: 'home',
    materials_needed: ['App blockers', 'Alternative activities', 'Accountability partner']
  },
  {
    id: 'selfcare-009',
    title: 'Practice Gratitude Journaling Challenge',
    description: 'Write three daily gratitudes for 30 days. Share weekly highlights with other parents for mutual encouragement and perspective.',
    type: 'self_care',
    category: 'Mental Wellness',
    payout: 25,
    max_participants: 30,
    current_participants: 22,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'easy',
    time_estimate: '5 minutes daily',
    location_type: 'home',
    materials_needed: ['Journal', 'Pen', 'Quiet time']
  },
  {
    id: 'selfcare-010',
    title: 'Start Early Morning Self-Care Routine',
    description: 'Wake up 30 minutes early for personal time - exercise, meditation, reading, or creative work. Build sustainable morning routine.',
    type: 'self_care',
    category: 'Personal Development',
    payout: 35,
    max_participants: 15,
    current_participants: 11,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000).toISOString(),
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'medium',
    time_estimate: '30 minutes daily',
    location_type: 'home',
    materials_needed: ['Alarm clock', 'Self-care activities', 'Quiet space']
  },
  {
    id: 'selfcare-011',
    title: 'Complete Career Development Course',
    description: 'Take online course to advance your career while parenting. Set up study schedule around family needs and track progress.',
    type: 'self_care',
    category: 'Professional Development',
    payout: 85,
    max_participants: 6,
    current_participants: 4,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString(),
    is_sponsored: true,
    sponsor_name: 'SkillForward Learning',
    difficulty: 'hard',
    time_estimate: '3-5 hours weekly',
    location_type: 'online',
    materials_needed: ['Computer', 'Course materials', 'Study schedule']
  },
  {
    id: 'selfcare-012',
    title: 'Join Parent Walking Group',
    description: 'Meet other parents for regular walks while kids play or nap. Combine exercise with social connection and mutual support.',
    type: 'self_care',
    category: 'Physical Wellness',
    payout: 20,
    max_participants: 10,
    current_participants: 7,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: null,
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'easy',
    time_estimate: '1 hour 3x weekly',
    location_type: 'local',
    materials_needed: ['Walking shoes', 'Weather gear', 'Stroller (if needed)']
  },
  {
    id: 'selfcare-013',
    title: 'Practice Mindful Parenting Techniques',
    description: 'Learn and implement mindful parenting strategies. Share experiences and challenges with other parents in similar journey.',
    type: 'self_care',
    category: 'Parenting Growth',
    payout: 45,
    max_participants: 8,
    current_participants: 6,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: new Date(Date.now() + 28 * 24 * 60 * 60 * 1000).toISOString(),
    is_sponsored: true,
    sponsor_name: 'Mindful Families Institute',
    difficulty: 'medium',
    time_estimate: '30 minutes daily practice',
    location_type: 'home',
    materials_needed: ['Mindfulness resources', 'Practice journal', 'Quiet space']
  },
  {
    id: 'selfcare-014',
    title: 'Learn Stress-Relief Cooking',
    description: 'Take up therapeutic cooking or baking as stress relief. Share recipes and techniques with other parents seeking healthy coping methods.',
    type: 'self_care',
    category: 'Creative Wellness',
    payout: 30,
    max_participants: 12,
    current_participants: 9,
    creator_id: 'system',
    status: 'active',
    created_at: new Date().toISOString(),
    deadline: null,
    is_sponsored: false,
    sponsor_name: null,
    difficulty: 'easy',
    time_estimate: '1-2 hours weekly',
    location_type: 'home',
    materials_needed: ['Cooking ingredients', 'Recipe collection', 'Kitchen tools']
  }
]

export const allTasks = [...soloTasks, ...communityTasks, ...selfCareTasks]

// Helper functions for task management
export function getTasksByCategory(category: string): TaskData[] {
  return allTasks.filter(task => task.category === category)
}

export function getTasksByType(type: 'solo' | 'shared' | 'self_care'): TaskData[] {
  return allTasks.filter(task => task.type === type)
}

export function getAvailableTasks(): TaskData[] {
  return allTasks.filter(task => 
    task.status === 'active' && 
    task.current_participants < task.max_participants
  )
}

export function calculatePlatformFee(payout: number, subscriptionTier: 'free' | 'pro' | 'premium'): number {
  const feeRates = {
    free: 0.10,      // 10% fee
    pro: 0.07,       // 7% fee  
    premium: 0.05    // 5% fee
  }
  
  return payout * feeRates[subscriptionTier]
}

export function getNetEarnings(payout: number, subscriptionTier: 'free' | 'pro' | 'premium'): number {
  const platformFee = calculatePlatformFee(payout, subscriptionTier)
  return payout - platformFee
}